// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUZdNjoOjH8pCkvmqZF7_572Tiu5vHqi4',
    appId: '1:163254635431:web:32d7c156068bbe2f968482',
    messagingSenderId: '163254635431',
    projectId: 'cmsc23-vjnicolas',
    authDomain: 'cmsc23-vjnicolas.firebaseapp.com',
    storageBucket: 'cmsc23-vjnicolas.appspot.com',
    measurementId: 'G-EJN5QD7JEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-67dNCtkgPcLk0-gGlUzX0IL_1S02cNw',
    appId: '1:163254635431:android:c3edcf0a80d4e633968482',
    messagingSenderId: '163254635431',
    projectId: 'cmsc23-vjnicolas',
    storageBucket: 'cmsc23-vjnicolas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArIN9l9MtK6rSMKu5e5uzOya58IEOsoS8',
    appId: '1:163254635431:ios:e70232cf99d14876968482',
    messagingSenderId: '163254635431',
    projectId: 'cmsc23-vjnicolas',
    storageBucket: 'cmsc23-vjnicolas.appspot.com',
    iosClientId: '163254635431-e4pcu7fn1g5mfkotq7bmb761oc86b6k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArIN9l9MtK6rSMKu5e5uzOya58IEOsoS8',
    appId: '1:163254635431:ios:e70232cf99d14876968482',
    messagingSenderId: '163254635431',
    projectId: 'cmsc23-vjnicolas',
    storageBucket: 'cmsc23-vjnicolas.appspot.com',
    iosClientId: '163254635431-e4pcu7fn1g5mfkotq7bmb761oc86b6k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
